"""
Django settings for RumorValidator project.

Generated by 'django-admin startproject' using Django 3.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '!yyj7j6rhf=b-pzvolj*9350p$o%cf6ys1^1_f!(2@5k(jjz(!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['rumor.com', 'www.rumor.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #third party
    'django_hosts',
    #custom app
    'Rumor',
    'Volunteer',
]

MIDDLEWARE = [
    'django_hosts.middleware.HostsRequestMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_hosts.middleware.HostsResponseMiddleware',
]
AUTH_USER_MODEL = 'Volunteer.Volunteer'
ROOT_URLCONF = 'RumorValidator.urls'
ROOT_HOSTCONF = 'RumorValidator.hosts'
DEFAULT_HOST = 'www'
DEFAULT_REDIRECT_URL = "http://www.rumor.com"
PROVINCE_CHOICES =(('HB', u'湖北'), ('BJ', u'北京'), ('SH', u'上海'), ('CQ', u'重庆'),
                   ('HuN', u'湖南'), ('SC', u'四川'), ('HeN', u'河南'), ('AH', u'安徽'),
                   ('JS', u'江苏'), ('SD', u'山东'), ('ZJ', u'浙江'), ('FJ', u'福建'),
                   ('GD', u'广东'), ('AM', u'澳门'), ('HaiN', u'海南'), ('GX', u'广西'),
                   ('YN', u'云南'), ('GZ', u'贵州'), ('SX', u'陕西'), ('NX', u'宁夏'),
                   ('SaX', u'山西'), ('HeB', u'河北'), ('TJ', u'天津'), ('LN', u'辽宁'),
                   ('GL', u'吉林'), ('HLJ', u'黑龙江'), ('NMG', u'内蒙古'), ('XJ', u'新疆'),
                   ('JX', u'江西'), ('GS', u'甘肃'), ('XG', u'香港'), ('TW', u'台湾'),
                   ('QH', u'青海'), ('XZ', u'西藏'))

PROVINCE_DICTIONARYS ={'HB': u'湖北', 'BJ': u'北京', 'SH': u'上海', 'CQ': u'重庆',
                       'HuN': u'湖南', 'SC': u'四川', 'HeN': u'河南', 'AH': u'安徽',
                       'JS': u'江苏', 'SD': u'山东', 'ZJ': u'浙江', 'FJ': u'福建',
                       'GD': u'广东', 'AM': u'澳门', 'HaiN': u'海南', 'GX': u'广西',
                       'YN': u'云南', 'GZ': u'贵州', 'SX': u'陕西', 'NX': u'宁夏',
                       'SaX': u'山西', 'HeB': u'河北', 'TJ': u'天津', 'LN': u'辽宁',
                       'GL': u'吉林', 'HLJ': u'黑龙江', 'NMG': u'内蒙古', 'XJ': u'新疆',
                       'JX': u'江西', 'GS': u'甘肃', 'XG': u'香港', 'TW': u'台湾',
                       'QH': u'青海', 'XZ': u'西藏'}
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'RumorValidator.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
